### ISSUE TITLE
[PD] Key learnings about difficult workplace conversations

### ISSUE THREAD

**Issue by esma-g** [CodeYourFuture/Module-JS3#24]
### Coursework content

Read the following materials about difficult workplace conversations. Write a 250-word essay about your key learnings from the PD session and these two articles.

- [How To Have Difficult Conversations At Work](https://www.forbes.com/sites/ashiraprossack1/2018/10/28/how-to-have-difficult-conversations-at-work/?sh=49b0cee810b7)
- [How to Have Difficult Conversations](https://www.psychologytoday.com/us/blog/some-assembly-required/201703/how-have-difficult-conversations)

### Estimated time in hours (PD has max 4 per week total)

1

### What is the purpose of this assignment?

When you complete this assignment you will have developed your own opinions and be better equipped to have effective conservations in difficult situations in your professional life.

### How to submit

Attach the link of your Google doc to this ticket on your board.

**Comment by ali-nasir-ali** [comment]
[https://docs.google.com/document/d/1OuTsTvaUbs5RLrasvdRogZD9ufUAov3U_YWkYzFIZAA/edit?usp=sharing](url)

**Comment by HarounAlarabi** [comment]
https://docs.google.com/document/d/1QlMYSqLFZYxQKBHBImMDwesALwqvavqN5x9jKU1PsGs/edit?usp=sharing

**Comment by kfklein15** [comment]
this exercise is moving to a different week in the new Curriculum
