### ISSUE TITLE
[PD] Giving constructive feedback

### ISSUE THREAD

**Issue by esma-g** [CodeYourFuture/Module-JS3#34]
### Coursework content

Imagine yourself in the following scenarios. How would you prepare to give constructive feedback in that situation? Write a short paragraph explaining what you would do or write a dialogue between you and the person you are giving feedback.

Scenarios:

- Your colleague took your lunch from the office fridge
- Your colleague keeps interrupting you and others in meetings
- Your flatmate left dirty cups in the sink for several days

### Estimated time in hours (PD has max 4 per week total)

1

### What is the purpose of this assignment?

This assignment aims to build on the exercises you worked on during the class. When you complete this assignment you will have thought more about the nature of the constructive feedback and reinforce your skills by putting them in writing.

### How to submit

Attach the link of your Google doc to this ticket on your board.

**Comment by ali-nasir-ali** [comment]
[https://docs.google.com/document/d/1vc-v5QvF2NxAHdfFXQmvwDPnlqrJmKfKouml6dlxvEw/edit?usp=sharing](url)

**Comment by DelniaAlipour** [comment]
**Link to Google Doc:**

https://docs.google.com/document/d/1i3nbUYf6Is0uktbJirD1_NvIezWvlVCCHjrnB136dXQ/edit

**Comment by kfklein15** [comment]
Archiving this since it is not longer part of the new curriculum coursework.
