### ISSUE TITLE
[PD] Resilience learning points and suggestions 

### ISSUE THREAD

**Issue by esma-g** [CodeYourFuture/Module-JS3#37]
### Coursework content

Watch the following video and read the articles. How do you think CYF can improve the PD session on resilience? Share 5 of your own learning points and 3 new suggestions for us to make the session even better.

- [Listening to shame](https://www.ted.com/talks/brene_brown_listening_to_shame/comments)
- [Growth Mindset + Vulnerability](https://medium.com/teachers-on-fire/growth-mindset-vulnerability-c956512286)
- [Failure, vulnerability, and the true nature of change](https://www.impactinternational.com/blog/2022/09/failure-vulnerability-and-true-nature-change)

### Estimated time in hours (PD has max 4 per week total)

1

### What is the purpose of this assignment?

This assignment will help you deepen your understanding of resilience, strengthen your skills, and support future cohorts that will attend CYF.

### How to submit

Attach the link of your Google doc to this ticket on your board.

### Anything else?

Optional video list:
[The benefits of failure](https://www.ted.com/playlists/418/the_benefits_of_failure)

**Comment by HereshT** [comment]
https://docs.google.com/document/d/105bTTIy8vS44w8FsbCLixFhI0R63a40T6i4G8cmEf-I/edit#heading=h.lp90cdtv7gkh

**Comment by ali-nasir-ali** [comment]
https://docs.google.com/document/d/1EEndyw2XcT0NiGltIftD5oRQuDezMNTYVrz2NL8p4AQ/edit?usp=sharing

**Comment by kfklein15** [comment]
@HereshT and @ali-nasir-ali , you need to post the answer on YOUR issue on YOUR board, not on the template :)

**Comment by kfklein15** [comment]
Closing this issue since it will be moved to a different board in the new curriculum
